services:
  # zipkin:
  #   image: openzipkin/zipkin
  #   ports:
  #     - "9411:9411"
  #   depends_on: [otel-collector]
  #   networks:
  #     - internal
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:0.111.0
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   networks:
  #     - internal
  chroma_db:
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    networks:
      - internal
    # depends_on:
    #   - otel-collector
    #   - zipkin

networks:
  internal:

volumes:
  chroma_data:
